export enum Collection {
  AZUKI = "0xED5AF388653567Af2F388E6224dC7C4b3241C544",
  BEANZ = "0x306b1ea3ecdf94aB739F1910bbda052Ed4A9f949",
  ELEMENTAL = "0xB6a37b5d14D502c3Ab0Ae6f3a0E058BC9517786e",
}

export enum EmblemId {
  AZUKI = "azuki",
  GOLD = "gold",
  SPIRIT = "spirit",
  FROG = "frog",
  RED_PANDA = "red-panda",
  CAT = "cat",
  SLOTH = "sloth",
  FIREFLIES = "fireflies",
  BUTTERFLY = "butterfly",
  FOX_FIRE = "fox-fire",
  SMOKE = "smoke",
  SAKURA = "sakura",
  LIGHTNING = "lightning",
  EARTH = "earth",
  FIRE = "fire",
  WATER = "water",
  KIGU = "kigu",
  DUALITY = "duality",
  ELEMENTAL = "elemental",
  ELEMENTAL_GOLD = "elemental-gold",
  "???" = "???",
  SHONEN = "shonen",
  ANIMAL = "animal",
  INFERNO = "inferno",
  TORRENT = "torrent",
  TECTONIC = "tectonic",
  SURGE = "surge",
  FORCE_OF_NATURE = "force-of-nature",
  ELEMENTAL_KIGU = "elemental-kigu",
  POLARITY = "polarity",
  BEANZ = "beanz",
  GOLD_BEANZ = "gold-beanz",
  SPIRIT_BEANZ = "spirit-beanz",
  SPECIAL_SEEDLINGS = "special-seedlings",
  BEANZ_ELEMENTS = "beanz-elements",
  BEANZ_KIGU = "beanz-kigu",
}

export enum EmblemType {
  AZUKI = "azuki",
  ELEMENTAL = "elemental",
  BEANZ = "beanz",
  FAVOURITES = "favourites",
}
