const config = {
  ALCHEMY_ID: process.env.NEXT_PUBLIC_ALCHEMY_ID,
  WALLETCONNECT_PROJECT_ID: process.env.NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID,
  RESERVOIR_API_KEY: process.env.NEXT_PUBLIC_RESERVOIR_API_KEY,
  MOBILE_BREAKPOINT: 768,
  TABLET_BREAKPOINT: 1024,
};

export default config;
